### ISSUE TITLE
command line params correctly

### ISSUE THREAD

**Issue by erangt** [wakeful/selenium_grid_exporter#2]
Hi,
I didnt understand if you want to run it with docker as service 

so 

docker run -d  -p 9090:9090 wakeful/selenium-grid-exporter "listen-address:9090" "scrape-uri http://localhost:4444/grid/api/hub"

Which url you need there ? how exactly the command line should be?

**Comment by wakeful** [comment]
`--scrape-uri` should point at you `selenium grid` instance - please check the sample [sample docker-compose](https://github.com/wakeful/selenium_grid_exporter/blob/master/docker-compose.yml#L33) project.

**Comment by erangt** [comment]
Ok so it's should work with this command : docker run -d -p 9090:9090 wakeful/selenium-grid-exporter "listen-address:9090" "scrape-uri http://localhost:4444/grid/api/hub"

But I didn't see any metrics when i curl it on 9090.

**Comment by wakeful** [comment]
you sure that selenium grid is running on this address `http://localhost:4444/grid/api/hub`? you need to pass the correct url for `selenium grid / hub` from the container perspective, I doubt you are running selenium grid inside the same container - so the `url` is wrong, `localhost` part should be replace with `hostname / IP` address of the box where `selenium grid` is running. This exporter will also append [/grid/api/hub](https://github.com/wakeful/selenium_grid_exporter/blob/master/selenium_grid_exporter.go#L134) to the `url`

**Comment by erangt** [comment]
yes if i curl http://localhost:4444/grid/api/hub i got the grid info. i talking about inside a machine that selenuim hub installed with docker-compose and also i run your docker.

**Comment by wakeful** [comment]
as I mention before you need to point the `exporter` at host / IP address of `selenium grid` - `localhost` works for your "main OS" as you are exposing `selenium grid` port to `localhost`, please see included  docker compose for full example -> https://github.com/wakeful/selenium_grid_exporter/blob/master/docker-compose.yml

**Comment by erangt** [comment]
I want to make me more clear.. I have machine that running  selenium hub inside and I want to take the metrics from this . So if I running inside this machine on localhsot I got the grid info so what the problem to use localhost as params for your docker exporter ? In other machine I need to curl with the ip ....

**Comment by wakeful** [comment]
exporter is running inside docker container so `localhost` will be pointing at the container itself and not your machine that is running selenium grid.

**Comment by erangt** [comment]
Ok also when I used in the url the machine ip and try to curl the metrics I got Connection refused.
